const { OpenAI } = require("openai")
const apiKey = require("../../configs/api_keys").OPENAI_API_KEY;
const openai = new OpenAI({ apiKey: apiKey });
const { extractAnArrayFromString, generateUserPrompt } = require("./utils/topic_utils.js")
const { generateLMContent, generateTextMessageResponseContent, generateAutoGeneratedAnswersForPostResponseContent } = require('./utils/love_message_utils.js')
const { generateTagPrompt, gene } = require('./utils/tags_utils.js')
const { generateConversationCreatorPromp, separateTitleAndDescription } = require('./utils/conversation_creator_utils.js')
const { rankPost } = require('./module/gpt_assistant/post_rank/index.js');
const { rankingPostPrompt, RankPostSystemMessage }  = require ("./utils/ranking_post_utils.js"); 
/**
 * Generate Topics using `gpt-3.5-turbo`
 * @param {String} data - Title of the post 
 * @returns {Array<String>[]} - Array of topics generated by the GPT-3 API
 */
const generateTopics = async (data) => {

    const userPrompt = generateUserPrompt(data);
    // Generate topics using OpenAI API
    const response = await openai.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages: [
            { role: "system", content: "You are a helpful assistant." },
            { role: "user", content: userPrompt },
        ],
        temperature: 0.8,
        max_tokens: 150,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0.6,
    });

    if (!response || !response.choices || !response.choices[0] || !response.choices[0].message || !response.choices[0].message.content) {
        throw new Error("OpenAI API did not return a valid response");
    }
    // Extract topics from generated string using regular expression
    const message = response.choices[0];
    const json = message.message;
    const content = JSON.stringify(json.content);
    const tags = extractAnArrayFromString(content);
    return tags;
};





/**
 * Love Message Generator  using `gpt-3.5-turbo`
 * @param {{by: String, message: String}} data - Data object 
 * @returns {Promise<String>} - Love message generated
 */
const generateLoveMessage = async (data) => {
    const userPrompt = generateLMContent(data.message);
    const userSaidPrompt = data.by.trim().length > 0 ? `${data.by} said: ` : '';
    // Generate topics using OpenAI API
    const response = await openai.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages: [
            { role: "system", content: "You are Message generator" },
            { role: "user", content: `${userSaidPrompt}${userPrompt}` },
        ],
        temperature: 0.8,
        max_tokens: 150,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0.6,
    });

    if (!response || !response.choices || !response.choices[0] || !response.choices[0].message || !response.choices[0].message.content) {
        throw new Error("OpenAI API did not return a valid response");
    }

    // Extract topics from generated string using regular expression
    const message = response.choices[0];
    return message.message.content;
}

/**
 * Girlz Bestie bot Message Generator 
 * 
 * @param {String} data - actual message from the user
 * @returns {Promise<String>} - Bot generated reponse message
 */
const generateGirlzBestieBotMessage = async (data) => {
    const userPrompt = generateTextMessageResponseContent(data);
    // Generate topics using OpenAI API
    const response = await openai.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages: [
            { role: "system", content: "You are Message generator" },
            { role: "user", content: userPrompt },
        ],
        temperature: 0.8,
        max_tokens: 150,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0.6,
    });

    if (!response || !response.choices || !response.choices[0] || !response.choices[0].message || !response.choices[0].message.content) {
        throw new Error("OpenAI API did not return a valid response");
    }

    // Extract topics from generated string using regular expression
    const message = response.choices[0];
    return message.message.content;
}

/**
 * Generate Tags according to the title || Description of the post
 * 
 * @param {String} data - Title || Description of the post
 */
const generateAiAnswersToPost = async (data) => {
    const userPrompt = generateAutoGeneratedAnswersForPostResponseContent(data);
    // Generate topics using OpenAI API
    const response = await openai.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages: [
            { role: "system", content: "You are a helpful assistant." },
            { role: "user", content: userPrompt },
        ],
        temperature: 0.8,
        max_tokens: 150,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0.6,
    });

    console.log(`✅ ChatGpt Response is: ${response}`);


    if (!response || !response.choices || !response.choices[0] || !response.choices[0].message || !response.choices[0].message.content) {
        throw new Error("OpenAI API did not return a valid response");
    }
    // Extract topics from generated string using regular expression
    const message = response.choices[0];

    console.log(`✅ ChatGpt message is: ${message}`);

    const json = message.message;
    const content = JSON.stringify(json.content);
    console.log(`✅ ChatGpt content is: ${content}`);

    const answers = extractAnArrayFromString(content);
    console.log(`✅ ChatGpt answers is: ${answers}`);

    return answers;
}


/**
 * Generate Tags according to the title || Description of the post
 * 
 * @param {String} data - Title || Description of the post
 */
const generateTags = async (data) => {
    const userPrompt = generateTagPrompt(data);
    // Generate topics using OpenAI API
    const response = await openai.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages: [
            { role: "system", content: "You are a helpful assistant." },
            { role: "user", content: userPrompt },
        ],
        temperature: 0.8,
        max_tokens: 150,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0.6,
    });

    if (!response || !response.choices || !response.choices[0] || !response.choices[0].message || !response.choices[0].message.content) {
        throw new Error("OpenAI API did not return a valid response");
    }
    // Extract topics from generated string using regular expression
    const message = response.choices[0];
    const json = message.message;
    const content = JSON.stringify(json.content);
    const tags = extractAnArrayFromString(content);
    return tags;
}

/**
 * HTTPS for generateTags function
 * 
 * @param {Request} req - Request object
 * @param {Response} res - Response object
 * 
 * @returns {Promise<void>} - Promise that resolves when the response is sent
 */

const generateTagsHTTPS = async (req, res) => {

    /// extract input string from request body
    const inputString = req.body.content || req.query.content || req.params.content;

    try {

        if (!inputString) {
            throw new Error("Invalid request. content is required.");
        }

        /// generate tags from input string
        const tags = await generateTags(inputString);

        /// return response
        res.send({ statusCode: 200, message: `Generated tags for ${inputString}`, tags: tags });

    } catch (err) {
        console.log(err);
        res.send({ statusCode: 400, message: JSON.stringify(err) });
    }

};



/**
 * Generate Tags according to the title || Description of the post
 * 
 * @returns {Promise<{title: String, description: String}>} - Promise that resolves when the response is sent
 */
const createConversation = async () => {
    const userPrompt = generateConversationCreatorPromp();
    // Generate topics using OpenAI API
    const response = await openai.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages: [
            { role: "system", content: "You are a teenger conversation starter" },
            { role: "user", content: userPrompt },
        ],
        temperature: 0.8,
        max_tokens: 150,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0.6,
    });

    if (!response || !response.choices || !response.choices[0] || !response.choices[0].message || !response.choices[0].message.content) {
        throw new Error("OpenAI API did not return a valid response");
    }
    // Extract topics from generated string using regular expression
    const message = response.choices[0];
    const json = message.message;

    const textChoice = json.content;
    return separateTitleAndDescription(textChoice);



}

/**
 * HTTPS for generateTags function
 * 
 * @param {Request} req - Request object
 * @param {Response} res - Response object
 * 
 * @returns {Promise<void>} - Promise that resolves when the response is sent
 */
const createConversationHTTPS = async (req, res) => {


    try {

        /// generate tags from input string
        const titleDescriptions = await createConversation();

        /// return response
        res.send({ statusCode: 200, message: `Success`, ...titleDescriptions });

    } catch (err) {
        console.log(err);
        res.send({ statusCode: 400, message: JSON.stringify(err) });
    }

};



/**
 * Ranks a post as binary (0 or 1) using the OpenAI API.
 * @param {string} content - The content of the post
 * @returns {Promise<number?>} binaryWeight - The binary weight of the post. 1 is yes, 0 is no.
 */
const rankAPostAssistant = async (content) => {

    return await rankPost(openai, content);

}

/**
 * Rank A Post with GPT
 * 
 * @param {string} content - The content of the post
 * 
 * @returns {Promise<{binaryWeight: number}>} - Promise that resolves when the response is sent
 */
const rankAPostGPT = async (content) => {
    const userPrompt = rankingPostPrompt(content); // Filter out it in binary 0 or 1 $(content)
    const conversationInput = [
        { 'role': 'system', 'content': 'Classify the text as promotional (0) or non-promotional (1). Focus on identifying content that are promotions.' },
        { 'role': 'user', 'content': userPrompt },
    ];
    // Generate topics using OpenAI API
    const response = await openai.chat.completions.create({
        model: "gpt-3.5-turbo",
        messages:conversationInput,
        temperature: 0.8,
        max_tokens: 150,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0.6,
    });

    if (!response || !response.choices || !response.choices[0] || !response.choices[0].message || !response.choices[0].message.content) {
        throw new Error("OpenAI API did not return a valid response");
    } 

    console.log('response: ', response.choices[0].message.content);
    // Extract the binary weight (0 or 1) from the response
    const binaryWeight = response ? parseInt(response.choices[0].message.content) : null;

    if(isNaN(binaryWeight)) {
        return {binaryWeight: 1};
    }
    // Return the binary weight
    return {binaryWeight} ;
}


module.exports = {
    generateTopics,
    generateLoveMessage,
    generateTags,
    generateTagsHTTPS,
    createConversationHTTPS,
    generateGirlzBestieBotMessage,
    generateAiAnswersToPost,
    rankAPostAssistant,
    rankAPostGPT
}