

/**
 * Generates the content for the love message
 * 
 * @param {String} title - Title of the post 
 * @returns 
 */
const generateLMContent = (title) => {
    return `Write an answer to this post (5 lines max), and formulate an answer as if you were answering her as her best friend: ${title}`; 
    // return `Reply to this post with a helpful, thoughtful, kind response ${title}`; 
};


/**
 * Generates the content for the Girlz Bestie bot message
 * 
 * @param {String} title - actual message title
 * @returns 
 */
const generateTextMessageResponseContent = (title) => {
    return `keep the conversation (5 lines max), and formulate an answer as if you were answering her as her best friend, she said: ${title}`; 
};

/**
 * Generates the 3 auto generated answers on post content
 * 
 * @param {String} title - actual title content
 * @returns 
 */
const generateAutoGeneratedAnswersForPostResponseContent = (title) => {
    return `Generate 10 teenger comments (3 words max each) as if you were her bestie +emojis:, she said: ${title}.  Output should be in the format "answers = ['', '', '']"`; 
};

module.exports = {
    generateLMContent,
    generateTextMessageResponseContent,
    generateAutoGeneratedAnswersForPostResponseContent
}